version: '3'

services:
  nginx:
    image: nginx
    volumes:
      - ./src/InfoTrack.Demos.Composite.Nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src/InfoTrack.Demos.Composite.Nginx:/data/nginx:rw
    ports:
      - "8080:80"
    command: [nginx-debug, '-g', 'daemon off;']

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  composer:
    build:
      context: ./src/InfoTrack.Demos.Composite.Composer
      dockerfile: InfoTrack.Demos.Composite.Composer/Dockerfile

  netcoremvcapp:
    build:
      context: ./src/InfoTrack.Demos.Composite.NetCoreMvcApp
      dockerfile: InfoTrack.Demos.Composite.NetCoreMvcApp/Dockerfile

  nodeapp:
    build:
      context: ./src/InfoTrack.Demos.Composite.NodeApp
      dockerfile: Dockerfile