version: '2'

# Override any service to become external service
# IIS or Container or whatever

services:
  nginx:
    image: nginx
    stdin_open: true
    tty: true
    volumes:
      - ./src/InfoTrack.Demos.Composite.Nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src/InfoTrack.Demos.Composite.Nginx:/data/nginx:rw
    ports:
      - "8085:80"
    command: [nginx-debug, '-g', 'daemon off;']

  redis:
    image: redis:alpine
    stdin_open: true
    tty: true
    ports:
      - "6379:6379"

  composer:
    image: composite/composer
    stdin_open: true
    tty: true

  netcoremvcapp:
    image: composite/netcoremvcapp
    stdin_open: true
    tty: true

  nodeapp:
    image: composite/nodeapp
    stdin_open: true
    tty: true
